---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/auth/login":
    post:
      summary: Login user
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    data:
                      message: Logged in successfully.
                      token: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJmNjQ2ODM3NS1iM2NiLTQ1NTYtYmI2NC0wYTViZjZhNGY3NjYiLCJzdWIiOiI3NmQ5YTZhYy0wOTU0LTQ2ZDEtOWRjNy0wMjg4MDAwMGYxNGEiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE3NDEwNDU3MDgsImV4cCI6MTc0MTEzMjEwOH0.-PvNBKLCh1rcZ049oCWxgVpjnyl7YxH33xT6exn_izo
                      user:
                        id: 76d9a6ac-0954-46d1-9dc7-02880000f14a
                        email: test@test
                        full_name: Werner Gislason
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/auth/requests/login"
  "/api/auth/signup":
    post:
      summary: Sign up user
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    data:
                      message: Signed up successfully.
                      token: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJkNTFlYWM1Yy1kOWQ3LTQyMzEtOWEwOC1lMzhlMjY2NTIwODUiLCJzdWIiOiI0MjQ1NThmZC1lY2Y4LTRlMTMtOWYyMy0zM2QwMGU4ZDExZmUiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE3NDEwNDU3MDksImV4cCI6MTc0MTEzMjEwOX0.v4Mcd7EMyXhDBh55b85HMAaTxzvoEETudlBxMN0WkUs
                      user:
                        id: 424558fd-ecf8-4e13-9f23-33d00e8d11fe
                        email: teste@teste
                        full_name: 
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/auth/requests/signup"
  "/api/auth/logout":
    delete:
      summary: Logout User
      tags:
      - Auth
      security:
      - bearer_auth: []
      responses:
        '200':
          description: Successful
  "/api/v1/users/{id}":
    get:
      summary: Show Client User
      tags:
      - Client Users
      security:
      - bearer_auth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    data:
                      id: 8ef1ea41-e7a4-4a64-ade0-c275842aaa70
                      cpf: 
                      email: ulysses.metz@heathcote.test
                      full_name: Lenard Kuhlman DC
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      auth: Invalid email or password.
        '404':
          description: Not found
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      base:
                      - Couldn't find User with 'id'=not_an_id
                    request_id: aa62199e-3e09-4498-a301-1ae32149a311
    put:
      summary: Update Client User
      tags:
      - Client Users
      security:
      - bearer_auth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    data:
                      id: a9a5fe24-d26a-4ee6-b34d-880c00164fcc
                      cpf: '12496062095'
                      email: admin@acme.com
                      full_name: Dummy Name
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      auth: Invalid email or password.
        '404':
          description: Not found
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      base:
                      - Couldn't find User with 'id'=not_an_id
                    request_id: c3985604-0988-4f2b-a723-22b5bd45184b
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/v1/users/requests/update"
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
  schemas:
    auth:
      requests:
        login:
          title: User Login Request
          type: object
          properties:
            user:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
          required:
          - user
        signup:
          title: Create User Request
          type: object
          properties:
            user:
              type: object
              properties:
                full_name:
                  type: string
                  nullable: true
                cpf:
                  type: string
                  nullable: true
                email:
                  type: string
                password:
                  type: string
              required:
              - user
      responses:
        login:
          title: Create User Response
          type: object
          properties:
            data:
              message:
                type: string
              token:
                type: string
              user:
                "$ref": "#/components/schemas/v1/users/_common"
          required:
          - data
        signup:
          title: Create User Response
          type: object
          properties:
            data:
              message:
                type: string
              token:
                type: string
          required:
          - data
    common:
      pagination_meta:
        title: Pagination Meta
        type: object
        properties:
          current_page:
            type: integer
          total_pages:
            type: integer
          current_page_size:
            type: integer
          total:
            type: integer
        required:
        - current_page
        - total_pages
        - current_page_size
        - total
    v1:
      users:
        _common:
          title: User
          type: object
          additionalProperties: true
          properties:
            id:
              type: string
            full_name:
              type: string
            email:
              type: string
              nullable: true
        _private:
          title: User Private
          type: object
          additionalProperties: true
          properties:
            id:
              type: string
            full_name:
              type: string
            email:
              type: string
              nullable: true
            cpf:
              type: string
              nullable: true
        requests:
          update:
            title: Update User Request
            type: object
            properties:
              user:
                type: object
                properties:
                  full_name:
                    type: string
                  cpf:
                    type: string
                    nullable: true
                  email:
                    type: string
                    nullable: true
                required:
                - user
        responses:
          show:
            title: Show User Response
            type: object
            properties:
              data:
                "$ref": "#/components/schemas/v1/users/_private"
            required:
            - data
servers:
- url: http://{defaultHost}
