---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/auth/login":
    post:
      summary: Login user
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    data:
                      message: Logged in successfully.
                      token: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI5OWQ0MTRjMi00NWY5LTRiYzktYWZlZi04MjFkOWQwMjRkMWMiLCJzdWIiOiJlZWNjZjY1ZS00MTk2LTRhMzUtODUxOS0zYjEyYWY4NzU1NjgiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE3NDExMzA4NTAsImV4cCI6MTc0MTIxNzI1MH0.8s5XZERAPtvcLAlm4atPeanjx2yihCwCKBn8oT6ixug
                      user:
                        id: eeccf65e-4196-4a35-8519-3b12af875568
                        avatar:
                          id: 
                          attachment_id: 
                          content_type: 
                          url: 
                        email: test@test
                        full_name: Susanne Barton
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/auth/requests/login"
  "/api/auth/signup":
    post:
      summary: Sign up user
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    data:
                      message: Signed up successfully.
                      token: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI0OGEyNzI3MC01NDNmLTRmNjMtOTY1MC05YzM5Y2IzZWZlMzQiLCJzdWIiOiIxOTgyNzNlNC00ZDQxLTRiYTMtODViNi0wZGZmYTI0ZWExZDIiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE3NDExMzA4NTAsImV4cCI6MTc0MTIxNzI1MH0.II8YpMYhp8VT0vKugkHuNKg5Vy6thWXzusfr1zGqI2Q
                      user:
                        id: 198273e4-4d41-4ba3-85b6-0dffa24ea1d2
                        avatar:
                          id: 
                          attachment_id: 
                          content_type: 
                          url: 
                        email: teste@teste
                        full_name: 
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/auth/requests/signup"
  "/api/auth/logout":
    delete:
      summary: Logout User
      tags:
      - Auth
      security:
      - bearer_auth: []
      responses:
        '200':
          description: Successful
  "/api/v1/categories":
    get:
      summary: List Categories
      tags:
      - Categories
      security:
      - bearer_auth: []
      parameters:
      - name: search
        in: query
        schema:
          type: string
      - name: q[user_id_eq]
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Filter by user_id or global
          content:
            application/json:
              examples:
                Default:
                  value:
                    meta:
                      current_page: 1
                      total_pages: 1
                      current_page_size: 50
                      total: 1
                    data:
                    - id: 139f2914-7c78-4eb1-9a05-2256abbe2b5a
                      created_at: '2025-03-04T23:27:31.114Z'
                      description: Deleniti suscipit quo dolores.
                      name: Leo Kling
                      updated_at: '2025-03-04T23:27:31.114Z'
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      auth: You need to sign in or sign up before continuing.
    post:
      summary: Create Category
      tags:
      - Categories
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    data:
                      id: aa772ee7-59f9-4806-8e15-e58f811d49a3
                      created_at: 2025-03-04 23:28:51 UTC
                      description: dummy
                      name: dummy
                      updated_at: 2025-03-04 23:28:51 UTC
                      user:
                        id: de5639cb-cd72-4b22-a22b-4a8f246b8cfd
                        avatar:
                          id: 
                          attachment_id: 
                          content_type: 
                          url: 
                        email: ronda_altenwerth@damore.test
                        full_name: Dr. Gale Hoeger
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/v1/categories/requests/create"
  "/api/v1/users/{id}":
    get:
      summary: Show User
      tags:
      - Users
      security:
      - bearer_auth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    data:
                      id: bda7d0b3-a160-4a05-8150-479578ca8b39
                      avatar:
                        id: 
                        attachment_id: 
                        content_type: 
                        url: 
                      cpf: 
                      email: lamar.klein@roob.test
                      full_name: Ivory Gutmann
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      auth: You need to sign in or sign up before continuing.
        '404':
          description: Not found
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      base:
                      - Couldn't find User with 'id'=not_an_id
                    request_id: 510f0f5c-b681-4617-b960-4b8ebfa1a858
    put:
      summary: Update User
      tags:
      - Users
      security:
      - bearer_auth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    data:
                      id: f9a314c7-7d07-49a2-abe2-ea7fc3f33723
                      avatar:
                        id: 
                        attachment_id: 
                        content_type: 
                        url: 
                      cpf: '12496062095'
                      email: admin@acme.com
                      full_name: Dummy Name
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      auth: You need to sign in or sign up before continuing.
        '404':
          description: Not found
          content:
            application/json:
              examples:
                Default:
                  value:
                    errors:
                      base:
                      - Couldn't find User with 'id'=not_an_id
                    request_id: 19ba4f87-02ae-4cc8-a004-66875aba1d22
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/v1/users/requests/update"
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
  schemas:
    auth:
      requests:
        login:
          title: User Login Request
          type: object
          properties:
            user:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
          required:
          - user
        signup:
          title: Create User Request
          type: object
          properties:
            user:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                full_name:
                  type: string
              required:
              - email
              - password
      responses:
        login:
          title: Create User Response
          type: object
          properties:
            data:
              message:
                type: string
              token:
                type: string
              user:
                "$ref": "#/components/schemas/v1/users/_common"
          required:
          - data
        signup:
          title: Create User Response
          type: object
          properties:
            data:
              message:
                type: string
              token:
                type: string
          required:
          - data
    common:
      pagination_meta:
        title: Pagination Meta
        type: object
        properties:
          current_page:
            type: integer
          total_pages:
            type: integer
          current_page_size:
            type: integer
          total:
            type: integer
        required:
        - current_page
        - total_pages
        - current_page_size
        - total
    v1:
      categories:
        _common:
          title: Category
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            description:
              type: string
              nullable: true
            created_at:
              type: string
            updated_at:
              type: string
        _private:
          title: Category (private)
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            description:
              type: string
              nullable: true
            created_at:
              type: string
            updated_at:
              type: string
            user:
              "$ref": "#/components/schemas/v1/users/_common"
        responses:
          create:
            title: Create category response
            type: object
            properties:
              data:
                "$ref": "#/components/schemas/v1/categories/_private"
          index:
            title: Category index response
            type: object
            properties:
              data:
                type: array
                items:
                  "$ref": "#/components/schemas/v1/categories/_common"
              meta:
                "$ref": "#/components/schemas/common/pagination_meta"
            required:
            - meta
            - data
      users:
        _common:
          title: User
          type: object
          additionalProperties: true
          properties:
            id:
              type: string
            full_name:
              type: string
            email:
              type: string
              nullable: true
        _private:
          title: User Private
          type: object
          additionalProperties: true
          properties:
            id:
              type: string
            full_name:
              type: string
            email:
              type: string
              nullable: true
            cpf:
              type: string
              nullable: true
        requests:
          update:
            title: Update User Request
            type: object
            properties:
              user:
                type: object
                properties:
                  full_name:
                    type: string
                  cpf:
                    type: string
                    nullable: true
                  email:
                    type: string
                    nullable: true
                required:
                - user
        responses:
          show:
            title: Show User Response
            type: object
            properties:
              data:
                "$ref": "#/components/schemas/v1/users/_private"
            required:
            - data
servers:
- url: http://localhost:3000
