default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  host: <%= ENV.fetch("POSTGRES_HOST") %>
  port: <%= ENV.fetch("POSTGRES_PORT") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") %>

test:
  <<: *default
  database: orca_mais_api_test

production:
  primary: &primary_production
    <<: *default
    database: orca_mais_api_production
    username: orca_mais_api
    password: <%= ENV["ORCA_MAIS_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: orca_mais_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: orca_mais_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: orca_mais_api_production_cable
    migrations_paths: db/cable_migrate
